### ISSUE TITLE
wikiのAsyncのwait_all以下の記述ミス

### ISSUE THREAD

**Issue by Juna-Idler** [folt-a/godot-nesink#11]
https://github.com/folt-a/godot-nesink/wiki/Async#wait_alldrains-array-cancel-cancel--null---variant-static

wait_allから下の「以下と同じです:」のコード内で、余計な`wait_`のせいで自己言及しているようなコードになっている。

**Comment by ydipeepo** [comment]
修正されていないようでしたので直しておきました。
