### ISSUE TITLE
drainsにSignalを渡すとdisconnectedエラー

### ISSUE THREAD

**Issue by folt-a** [folt-a/godot-nesink#8]
環境
Windows10
Godot4.0 beta2

drainsに直接Signalを渡しSignalがemitされたときに、disconnectできないエラーが出ます。
処理自体は正常に完了しているように見えます。

```gdscript
	var res = await Async.wait_any([
		get_tree().create_timer(1).timeout,
		get_tree().create_timer(3).timeout,
	])
	print("finished!")
```

![image](https://user-images.githubusercontent.com/32963227/193482222-a7cff97c-43c0-4160-acf9-61dd7bdf900e.png)

Signalを直接ではなくAsync.from_signal()にするとうまくいくので、こちらを使った方が良いでしょうか？

---

res://addons/godot-nesink/NesinkronaFromSignalAsync.gdで、
CONNECT_ONE_SHOTの代わりに手動でシグナルをdisconnectするとエラーが消えますが、これが良い解決法なのかは分かりません！

```gdscript
func _init(
	signal_: Signal,
	signal_argc: int) -> void:

	assert(signal_argc <= MAX_SIGNAL_ARGC)

	match signal_argc:
		0: signal_.connect(_on_completed_0.bind(signal_))
		1: signal_.connect(_on_completed_1, CONNECT_ONE_SHOT)
		2: signal_.connect(_on_completed_2, CONNECT_ONE_SHOT)
		3: signal_.connect(_on_completed_3, CONNECT_ONE_SHOT)
		4: signal_.connect(_on_completed_4, CONNECT_ONE_SHOT)
		5: signal_.connect(_on_completed_5, CONNECT_ONE_SHOT)

func _on_completed_0(signal_:Signal) -> void:
	if is_pending:
		complete_release([])
	signal_.disconnect(_on_completed_0)
```

**Comment by ydipeepo** [comment]
前におっしゃってたのこういうのでしたか～!
確認したところ同じエラーでましたのでちょっと見てみます
```GDScript
await Async.from_signal(get_tree().create_timer(1.0).timeout).wait()
```

**Comment by ydipeepo** [comment]
9d08bab, 82d84a3 で修正しました

```GDScript
func _f(signal_: Signal) -> void:
    print(signal_.get_object()) # <Freed Object>
_f(get_tree().create_timer(1.0).timeout)
```
この問題私も困っていたんですが Signal にラップされた後 SceneTreeTimer が解放されてしまい (なぜか発火はするけど) 切断はできないで～てことみたいです。
このケース以外まだ確認してないですが SceneTreeTimer.timeout は解放されてても飛んでくるという特殊挙動だったのでそれ用のフロー設けて対処しました。

報告ありがとうございます。こちらに新しいバージョンを上げました:
- https://github.com/ydipeepo/godot-nesink/releases/tag/v1.0.2-beta

**Comment by folt-a** [comment]
うまくいきました！ありがとうございます！！
